### ISSUE TITLE
代码貌似不能实际使用，参考一下框架还不错

### ISSUE THREAD

**Issue by 20170819** [max-min/streams#1]
1）PS包没有结尾标识符号0x00, 0x00, 0x01, 0xb9
2）有时候网络接收来的包不一定是PS开头，可能是PES包一部分，也可能是几个PES包

**Comment by max-min** [comment]
1.再仔细看看代码，这个结尾符是在接收到数据后代码上添加的，方便后面解码跳出。
2.还是没仔细看，我说过这个解析是基于已经接收到一个[完整的帧](https://github.com/max-min/streams/blob/aa1b27243f6f51826732a8ed1f3ea211a2ad134c/packet/rtpdec.go#L22)，在上层业务，你还需要自己来处理rtp包的mark位或者时间戳变化等来判断一帧的结束，以及rtp乱序，重包等问题的。

**Comment by max-min** [comment]
close
