### ISSUE TITLE
是否可以不用bitreader库，而实现内存的零拷贝操作？

### ISSUE THREAD

**Issue by mask-pp** [max-min/streams#3]

**Comment by max-min** [comment]
是一个好的idea。 是啥好的库推荐或者比较好的实现策略么？

**Comment by mask-pp** [comment]
我基于streams更改了一版(https://github.com/mask-pp/rtp-ps.git)，为项目做的改动 变动较大，有缺点，涉及到bit层面的操作就不方便了

**Comment by max-min** [comment]
有用benchmark压测对比数据么？ 
相对来说，你这个少了一次数据拷贝。也考虑考虑把bit位的操作加上去。

**Comment by mask-pp** [comment]
倒没做压测，我想去除了一次数据拷贝性能上应该会快些，bit操作确实比较麻烦，细粒度太深性能上也很难不消耗，目前来看频繁细粒度操作不是很多 所以我就直接吧这个除了
