### ISSUE TITLE
请问如何使用vlc调试,可以直接接收H264码流,然后转PS,再转RTP么

### ISSUE THREAD

**Issue by yupeng2015** [max-min/streams#4]
请问如何封装音频

**Comment by max-min** [comment]
一样的哈，只是注意一下ps头媒体类型。

**Comment by zhh827** [comment]
请问使用 示例中 enc，源文件MP4格式，转换后不能播放。https://github.com/zhh827/gb28181Simulator， 这个带的示例中 test.dat 能播放，请问有什么需要配置的地方吗？
